### ISSUE TITLE
bug: `Betterfolders` & `FileContentPreview` plugins are broken

### ISSUE THREAD

**Issue by Rairof** [fres621/vendetta-plugins#8]
Been a while since you last updated your plugins and some your prominent plugins like `Betterfolders` & `FileContentPreview` have been broken for a long time now. Are there any plans on maintaining your plugins?

**Comment by fres621** [comment]
Thanks for your report! I had no idea that FileContentPreview wasn't working. I think it should be working now (not proxied yet)
about BetterFolders I'll check it out when I can but last time I tried i couldn't solve the issue. Let me know if you need anything else or if I should close this issue

**Comment by Rairof** [comment]
https://github.com/fres621/vendetta-plugins/issues/8#issuecomment-2105595319
That's it. Thanks fres
